### ISSUE TITLE
Publications data structure

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/knowledgegraph#2]
Currently, publications field returns a single object (sometimes), with an associated doi. We see in some of our existing datasets that it can contain multiple publications. Could it return as an array?

Additionally, we find it helpful, if in the publication field, an additional attribute (we are internally calling it citation) would help the front end immensely, so we can display something like:

```
<a href = " {{ publication.url }} "> {{ publication.citation }} </a>
```
which would translate to:
```
<a href = "http://www.sciencemag.org/content/340/6139/1472">Katrin Amunts et al, BigBrain: An Ultrahigh-Resolution 3D Human Brain Model, Science, 21. Juni 2013, Vol. 340, S. 1472-1475 </a>
```

**Comment by olinux** [comment]
Since we're generating the UI structure from our graph and can not be aware about the cardinality of a specific field, this is how it works: If it is only one entry, you get the data (as in the "usual" DOI case) as a single key-value pair. As soon as there are multiple items, the value becomes an array. This is a trade-off between a compact structure (because some properties will always contain only a single value) and having a dynamic system. 
The webapp (and any other client) needs to be aware that every value could either be a single value or an array and has to act accordingly (in fact, this decision triggers a different representation mode in the UI: single values are displayed directly, lists as bullet-points or character separated - depending on the additional directives given). 
About the citation: We currently don't have the data for this but would be able to present it as you suggest if this information is in the graph

**Comment by xgui3783** [comment]
understood.

Thanks for clearing it up with me.
